apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - orders-service/deployment.yaml
  - orders-service/service.yaml
  - products-service/deployment.yaml
  - products-service/service.yaml
