apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/your-username/OmniShop-Enterprise-Platform"
    targetRevision: "main"
    path: "k8s"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: devsecops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
