{{- range $key, $val := .Values.services }}
{{- if $val.serviceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $val.name }}-monitor
  namespace: {{ $.Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ $val.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
{{- end }}
