{{- range $key, $val := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $val.name }}
spec:
  selector:
    app: {{ $val.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ $val.port }}
  type: ClusterIP
{{- end }}
